#+TITLE: Igraph toolbox

Toolbox for integrating the [[https://igraph.org/][igraph]] C library with MATLAB.

See [[The documentation][https://davidrconnell.github.io/matlab-igraph]] for a more thorough introduction.

*In early development*: Still missing many features and may be buggy. Please report any crashes you have by opening an issue and feel free to make feature requests, suggest changes, or contribute. Additionally, you should not see any internal errors (i.e. error ids of the form ~Igraph:internal:something~), please open an issue if you find one.
Also note, I am not familiar with all the file formats supported by igraph, so if any of read/write logic is not sensible, let me know by opening an issue.

The igraph C library provides efficient graph analysis functions including graph generation, reading/writing graphs to file, and community detection.

This toolbox aims to provide a consistent API to perform graph analyses inside MATLAB while following MATLAB's conventions.

In MATLAB, graphs are stored as adjacency matrices.
By using standard matrices, it's easy to produce and process graphs using builtin functions.
Both full and sparse adjacency matrices are supported along with different data types (doubles and logicals for now).
This allows flexibility and easy integration into preexisting projects.

See the getting started live script in the toolbox for basic usage as well as the other example scripts. For more thorough introduction, see the "Using the toolbox", "Common functions", and "Basic API" sections of this README.

In addition to the toolbox, the ~mxIgraph~ interface library has been kept separate to allow developers access to the mex routines for bridging MATLAB and igraph.
Using this library you can wrap your own igraph based C functions with the mex API to run them in MATLAB.
For more information, see the ~README~ in the ~mxIgraph~ directory.

* Citation
If you publish results generated with the help of this package, make sure to cite igraph:

#+begin_quote
Csardi, G., & Nepusz, T. (2006). The igraph software package for complex network research. InterJournal, Complex Systems, 1695.
#+end_quote

* Installation
** Installing igraph C library
Currently the igraph C library must be compiled from the source tracked as a submodule in this repo.
It may be possible in the future to simplify the installation process by allowing the use of precompiled binaries.
Compiling from the submodule here will ensure the version works well with the toolbox and allows the use of different versions on different branches.

*** Compiling igraph from source
Before compiling from source you need to obtain the dependencies as declared in [[https://igraph.org/c/html/latest/igraph-Installation.html][igraph's installation instructions]].
Specifically you need:
- ~bison~
- ~flex~
- ~libxml2~
It is also recommended, but not required, to have the libraries:
- ~arpack~
- ~blas~
- ~glpk~
- ~gmp~
- ~lapack~
- ~plfit~
** Installing the toolbox
In addition to MATLAB, mex, and igraph, this toolbox depends on make.
To install the toolbox use ~make all~.
Compilation time can be improved using ~make -j all~ to run the make rules in parallel where possible.

Once the mex files have been compiled, ensure the toolbox is on MATLAB's path. In MATLAB, run ~addpath("path/to/matlab-igraph/toolbox");~.
You'll likely want to run ~savepath;~ as well so the toolbox will remain on MATLAB's path between restarts.
** Upgrading
Every once in awhile you will want to check for a new release by running ~git pull~ in the ~matlab-igraph~ directory.
If this pulled anything new down, rerun the above make commands.
** Installing the mxIgraph C library
~make mxIgraph~  can be used to exclusively compile the C library.
Since the toolbox does require this library, the above ~make all~ will also compile it.
The only reason to run this command is if all you want is the mxIgraph library and not the toolbox.
* See also
- [[https://igraph.org/][igraph homepage]]
- [[https://r.igraph.org][igraph R package]]
- [[https://python.igraph.org][igraph python package]]
- [[http://szhorvat.net/mathematica/IGraphM][igraph Mathmatica package]]
- [[https://igraph.org/c][igraph C library]]
