function rng(seed, generator)
%RNG modify the random number generator used by igraph.
%   RNG(SD) seeds the random number generator (RNG) with SD. The seed must be a
%   non-negative integer. When igraph is using MATLAB's RNG, seeds the
%   generator through MATLAB's builtin RNG function (and therefore will affect
%   MATLAB calls to random functions as well).
%
%   RNG(SD, GENERATOR) sets the generator used by igraph's default rng to
%   GENERATOR. GENERATOR can be one of:
%
%        Generator    Description
%      ----------------------------------------------------------------------
%       'MATLAB'      MATLAB's internal generator (default)
%       'MT19937'     Makoto Matsumoto and Takuji Nishimura variant of
%                     Merseene Twister
%       'glibc2'      GNU libc 2
%       'pcg32'       32-bit PCG random number generator
%       'pcg64'       64-bit PCG random number generator
%
%   By default, igraph will use MATLAB's RNG. This means seeding MATLAB's RNG
%   or changing the generator used by MATLAB's RNG will affect the random
%   numbers igraph produces. It also means running calling MATLAB functions
%   that use the default random number generator will impact the numbers
%   generated by igraph and vice-versa.
%
%   Setting igraph's RNG to one of the other options will decouple the
%   generators used by MATLAB and igraph.

    arguments
        seed {mustBeNonnegative, mustBeInteger}
        generator (1, :) char ...
            {igutils.mustBeMemberi(generator, ...
                                   {'matlab', 'mt19937', 'glibc2', 'pcg32', ...
                                    'pcg64', 'current'})} = 'current';
    end

    generator = mexIgraphDispatcher(mfilename(), seed, generator);

    if strcmp(generator, 'matlab')
        rng(seed);
    end
end
