name: Build

on:
  - workflow_call

jobs:
  build-macos-with-clangxx:
    name: Build macOS with clang++
    runs-on: macos-latest
    env:
      LLVM_VERSION: "14.0.5"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
        run: brew install autoconf automake libtool

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Build toolbox
        run: |
          cmake -B build . -G Ninja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            --install-prefix=${GITHUB_WORKSPACE}/dist \
            -DCMAKE_PACKAGE_VERSION="${{ github.ref_name }}"
          cmake --build build
          cmake --install build

      - name: Package dist
        run: cmake --build build --target package

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: matlab-igraph-${{ runner.os }}-arm-${{ github.sha }}
          path: build/matlab-igraph_*.tar.gz

  build-macos-with-clang:
    name: Build macOS with clang
    runs-on: macos-latest
    env:
      LLVM_VERSION: "14.0.5"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
        run: brew install autoconf automake libtool

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Build toolbox
        run: |
          cmake -B build . -G Ninja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang \
            --install-prefix=${GITHUB_WORKSPACE}/dist \
            -DCMAKE_PACKAGE_VERSION="${{ github.ref_name }}"
          cmake --build build
          cmake --install build

      - name: Package dist
        run: cmake --build build --target package

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: matlab-igraph-${{ runner.os }}-intel-${{ github.sha }}
          path: build/matlab-igraph_*.tar.gz
