name: MATLAB

on:
  push:
    branches: [ simplify-compilation ]
    # tags:
    #   - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  checks: write
  pull-requests: write

# TODO: Add matrix for different OSes
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Pull submodules
        run: git submodule init && git submodule update

      - name: Install linux dependencies
        if: runner.os == 'Linux'
        run: >
          sudo apt update && sudo apt upgrade &&
          sudo apt install cmake gcc g++ libxml2-dev libgmp-dev libglpk-dev
          libarpack2-dev libplfit-dev libopenblas64-dev libbison-dev libfl-dev

      - name: Install windows dependencies
        if: runner.os == 'windows'
        run: >
          git clone "https://github.com/microsoft/vcpkg" &&
          .\vcpkg\bootstrap-vcpkg.bat &&
          .\vcpkg\vcpkg install libxml2:x64-windows

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Build toolbox Linux
        if: runner.os == 'Linux'
        run: >
          LD_LIBRARY_PATH=/usr/local/MATLAB/R2023b/sys/os/glnxa64
          make -j toolbox

      - name: Build toolbox windows
        if: runner.os == 'windows'
        env:
          IGRAPH_OPTIONS: "-DCMAKE_TOOLCHAIN_FILE=./vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake"
          PWD: ${{ github.workspace }}
        run: >
          make -j toolbox

      - name: Run tests and generate artifacts
        env:
          PWD: ${{ github.workspace }}
        run: make -j check

      - name: Upload Linux test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: runner.os == 'Linux'
        with:
          files: build/tests/*.xml

      - name: Upload macos/windows test results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: runner.os != 'Linux'
        with:
          files: build/tests/*.xml

      - name: Make docs
        run: make -j docs

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: matlab-docs-${{ github.sha }}
          path: docs/

      - name: Package dist
        env:
          PWD: ${{ github.workspace }}
        run: make dist

      - name: Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: Release ${{ github.ref }}
          workdir: ${{github.workspace}}/dist
