name: Publish docs

on:
  - workflow_call

jobs:
  publish:
    name: Publish docs
    runs-on: ubuntu-20.04

    steps:
      - name: Start virtual display
        run: |
          sudo apt-get install xvfb
          Xvfb :99 & echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b

      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Run make docs task
        uses: matlab-actions/run-build@v2
        with:
          tasks: makeDocs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: matlab-igraph-docs-${{ github.sha }}
          path: ./docs
