name: Release Packages

on:
  push:
    branches:
      - devel
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  checks: write
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  build-toolbox:
    uses: ./.github/workflows/build.yaml

  publish-docs:
    if: ${{ github.ref_type == 'tag' }}
    uses: ./.github/workflows/publish.yaml

  deploy-site:
    if: ${{ github.ref_type == 'tag' }}
    needs: publish-docs
    uses: ./.github/workflows/hugo.yaml

  release:
    name: Release new packages
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    needs: build-toolbox
    env:
      TAG_NAME: ${{ github.ref_name }}

    steps:
      - name: Create release name
        run: echo RELEASE_NAME=${TAG_NAME/v/matlab-igraph } >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Create release notes
        run: |
          range=$(grep --max-count=2 --line-number "## \[" < CHANGELOG.md |\
            cut -f 1 -d: | tr '\n' ',' | sed -n 's/,$/p\n/p')
          sed -n $range < CHANGELOG.md | head -n-2 | tail -n+3 > release_notes.md
          sed -i 's/###/##/g' release_notes.md

      - name: Collect package
        uses: actions/download-artifact@v4
        with:
          name: matlab-igraph-toolbox-${{ github.sha }}
          path: release

      - name: Upload assets to release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          bodyFile: release_notes.md
          artifacts: release/*
